### ISSUE TITLE
*botFilePath* and *botFileSecret* missing locations

### ISSUE THREAD

**Issue by Ahmedalkazaz** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#1]
I wish to highlight  that parts of the current material seems to be relying on features that are already deprecated by Azure. In particular I refer to a very important architectural change that invalidates the current material when version we have. Azure has changed the way it authenticate the bots, in the past it was relying on `botFilePath` and `botFileSecret` located in **App Service Settings**. The material constantly refer to this for instance:

01-	In the lab files:
![image01](https://user-images.githubusercontent.com/29112895/57966114-dd933200-791b-11e9-8751-75b6f2f4a4a6.jpg)

02-	In the Instructor Guide they refer to the same settings:

![image02](https://user-images.githubusercontent.com/29112895/57966115-dd933200-791b-11e9-80d5-038afdc597a2.jpg)

Now the contents of this page has been deemed by Azure “Classic” in other it’s being deprecated and not supporting the same structure that’s being referred to in the labs.
 ![image03](https://user-images.githubusercontent.com/29112895/57966113-dd933200-791b-11e9-870b-ab619b7a18f4.jpg)
This issue has been blogged online and developers are already moving away from using the old architecture as it’s not supported anymore by Azure’s online offering.
https://stackoverflow.com/questions/55473167/azure-bot-services-templates-botfilepath-botfilesecret-fields-are-missing-n

**Comment by j-ankur** [comment]
Yes you are right. In fact the downloaded source doesn't have certain files which were mentioned in the lab guide. To be precise in the following step:

"You can also remove "**EchoBotWithCounter.ruleset**" from the root project directory, as that's what the packages are used to create."

The above mentioned file is not present in the solution. Likewise in the below step:

Rename"**CounterState.cs**" to "PictureState.cs", the former file is missing.

Most of the steps in this lab are not accurate and doesn't allows to move ahead with the lab.

**Comment by givenscj** [comment]
Hi there, yes, the Aug 2019 course refresh will address this architectural change in the bot framework and deployment methodology.

**Comment by givenscj** [comment]
The latest labs and updates have been posted, please let us know how you like them.
