### ISSUE TITLE
Lab 08 is missing

### ISSUE THREAD

**Issue by Ahmedalkazaz** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#2]
Lab 08 is missing and Lab 09 depends on it.

![lab08](https://user-images.githubusercontent.com/29112895/57970022-1813c380-794a-11e9-972f-ba035d321452.png)

**Comment by ac2707** [comment]
could proceed with Lab 9 ... though no update on lab 8 - is it under construction like Lab 5 ?

**Comment by givenscj** [comment]
Hi there, this lab will be available next week in the Aug 2019 refresh.

**Comment by givenscj** [comment]
The latest labs and updates have been posted, please let us know how you like them.
