### ISSUE TITLE
Lab 5.4 out of date code location

### ISSUE THREAD

**Issue by ArmandoLacerda** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#25]
I've recently downloaded the QnA code from the portal and the code bits location on the lab 5.4 don't match the new VS Project. Please update.

The method call is also omitting the optional parameters.

**Comment by gerryaobrien** [comment]
Updated the lab instructions to remove code snippets.  The auto-generated code from the QnA Maker tool can, and will, change based on the framework and SDK versions and when the development team makes changes to the way the code is generated.
