### ISSUE TITLE
error MSB4019

### ISSUE THREAD

**Issue by MaksymShmaryha** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#26]
When i Try to "dotnet run" the TestCLI, i get this error:
...\ProcessingLibrary\ProcessingLibrary.csproj(71,3): error MSB4019: The imported project <...> was not found. Confirm that the expression in the Import declaration is correct, and that the file <...> exists on disk.
I'm using Visual Studio Professional 2019, did all the updates. Google says that MSB4019 is due to the Portable library that is no longer supported by the VS 2019. I tried every suggestion, every update... nothing. Can you please help me?

**Comment by gerryaobrien** [comment]
The labs were not designed for dotnet core.

Future lab updates will address this
