### ISSUE TITLE
Issue while running lab-3

### ISSUE THREAD

**Issue by kiranbeethoju** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#27]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Users\kirankumar.beethoju\Documents\Azure\AI-100-Design-Implement-Azure-AISol-master\Lab3-Basic_Filter_Bot\code\Finished\PictureBot\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	C:\Users\kirankumar.beethoju\Documents\Azure\AI-100-Design-Implement-Azure-AISol-master\Lab3-Basic_Filter_Bot\code\Finished\PictureBot\PictureBot.sln	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234

**Comment by gerryaobrien** [comment]
Are you following this lab as part of the classroom-based training?
