### ISSUE TITLE
Lab 7 code snippet missing SearchPics

### ISSUE THREAD

**Issue by madiepev** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#29]
In lab 7.2 a case for SearchPics is missing. For example, add:
case "SearchPics":
                                await SearchResponses.ReplyWithSearchConfirmation(stepContext.Context, result.Text);
                                await MainResponses.ReplyWithLuisScore(stepContext.Context, topIntent.Value.intent, topIntent.Value.score);
                                break;

**Comment by gerryaobrien** [comment]
This is not an issue, it just wasn't added as part of the lab.  Feel free to add it if you want to test the full functionality.
