### ISSUE TITLE
Lab 9 - console output

### ISSUE THREAD

**Issue by ac2707** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#3]
on running the the console app created with the given code in the lab, and echo bot created in azure, the console output is that of echo bot as below and not as shown in the lab .. please advise.
![image](https://user-images.githubusercontent.com/49182510/59752613-36017a80-92a0-11e9-8e61-ed01a7745b39.png)

scrreenshot from lab ;
![image](https://user-images.githubusercontent.com/49182510/59752877-a01a1f80-92a0-11e9-99b1-57e2b1b97c95.png)

**Comment by givenscj** [comment]
Hi there,

In the updated labs you now have a step that ensures you publish your picture bot to the app service endpoint for direct line testing.  The updated labs will be available sometime next week!

**Comment by givenscj** [comment]
Additionally, you will want to ensure that you check the "remove extra files" checkbox in the publish setting.
