### ISSUE TITLE
Lab 7 searchDialog doesn't exist

### ISSUE THREAD

**Issue by madiepev** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#30]
In Lab 7 we refer to the searchDialog in the Regex part. The searchDialog doesn't exist and even the Regex itself is never used, everything is always going to default and thus to LUIS. It seems unnecessary to have this part in. Why not just have the LUIS part?

**Comment by gerryaobrien** [comment]
It is there for potential future use.  Just ignore the code that isn't covered in the lab steps.
