### ISSUE TITLE
Not repo found.

### ISSUE THREAD

**Issue by Torebor** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#32]
The url for " There are some directories in the [main](https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/blob/master/Lab2-Implement_Computer_Vision/Lab2-Implement_Computer_Vision) github repo folder" In the ab 2.2: Resources section redirects to a broken link.

This is the right one I guess: https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/tree/master/Lab2-Implement_Computer_Vision

**Comment by gerryaobrien** [comment]
Link updated
