### ISSUE TITLE
Update lab 3 instructions to specify bot correct project template

### ISSUE THREAD

**Issue by iamalexmang** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#33]
The latest version of the Visual Studio Extension adds Bot project templates for multiple .NET Core framework versions. Selecting the wrong one blocks students at an upcoming step. It is of the upmost importance that the correct version is selected, which is why it's important that (1) the https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/raw/master/images/NewBotProject.png screen capture is updated and that (2) the correct template name (including the .NET Core version) is specified in the instruction.

**Comment by gerryaobrien** [comment]
Sorry, I just stepped through the lab and had no issues.  Likely because I am already familiar with the lab.   Can you provide more clarity on the issues you are experiencing?  This lab is intended to be used with the lab hosting environment that is configured for the labs to work.  

If you are not using the hosted environment and creating your own, you will need to provide support for that environment.

Please outline the specific errors you are encountering.

**Comment by iamalexmang** [comment]
Sure! LODS no longer seem to have .NET Core 2.2 installed.
However, using the latest version of the extension in Visual Studio, two Echo Bot templates exist (as opposed to a single one when the screenshots were taken and the lab was authored). The result is that half of my students thought that they should choose the Echo Bot (Bot Framework v4) (.NET Core 2.2) option as that was the first one which appeared in the list. Following the instruction, they were struggling to figure out why their solution didn't compile and have spend 30 minutes or more installing SDKs, rebooting the LODS VM and getting aggravated with the situation.
I've opened the issue as I though you should be aware of the situation and that updating the screenshot indicated above, as well as specifically mentioning that they should choose Echo Bot (Bot Framework v4) **(.NET Core 3.1)** might improve the experience dramatically.

**Comment by gerryaobrien** [comment]
Thanks for the clarification.  I'm not sure what changed in the LODS image where .NET Core is no longer installed.

However, it is not required in the Bot lab, which is not a Core app.

The screen shot for the VS 2019 steps, shows Echo Bot and not Core Bot.  If students are following the lab steps, and looking at the screen shot, the lab will work and not give errors.  I just validated it again by running the lab locally on my machine and the steps are correct as written.

I realize that there may be Core Bot templates added, however, the screen shot and lab instructions are correct as written and when followed as such, the lab will work.

**Comment by iamalexmang** [comment]
I'm sure you've tested it Gerry.
But students are selecting Echo Bot (Bot Framework v4) (.NET Core 2.2) and they can't build the solution on the LODS machine.
If they select Echo Bot (Bot Framework v4) (**.NET Core 3.1**) they don't have this issue and it saves them around 30 minutes or so.

**Comment by iamalexmang** [comment]
Here's a picture to what I'm referring to.
![image](https://user-images.githubusercontent.com/5773281/83247822-c896e300-a1ac-11ea-919a-d265cc32a8d5.png)

**Comment by iamalexmang** [comment]
I believe this one could be used directly. But the instructions as to which template should be selected should also be updated.

![image](https://user-images.githubusercontent.com/5773281/83247902-e95f3880-a1ac-11ea-96df-bc7a9476c83b.png)

**Comment by gerryaobrien** [comment]
I have updated the lab steps but have not changed the screen shot.  Apparently there are different versions of the templates depending on the install.  Everyone of my VS 2019 installs use the screen shot and template options that are displayed in the lab now.   I do not have multiple versions, like your screen shot depicts.

Closing this issue.
