### ISSUE TITLE
Update lab 7 instructions to add the 'ReplyWithSearchConfirmation' method to the Main response

### ISSUE THREAD

**Issue by iamalexmang** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#35]
Labs 3 and 4 instructions and finished sample code don't contain a method in the Main response which is referenced in Lab 7, namely the 'ReplyWithSearchConfirmation' method.
In lab 7, instructions are to update the MainMenuAsync switch block of code and this code contains a reference to the missing method.
I suggest that either we update all lab instructions up to 7 to also contain this method, or add instructions in the 7th lab (before 7.3, step 1) to also add the missing method.

Code which is missing is 
``` c#
        public static async Task ReplyWithSearchConfirmation(ITurnContext context)
        {
            await context.SendActivityAsync($"Searching your picture(s)...");
        }
```
This should be added in the MainResponses.cs class.

**Comment by gerryaobrien** [comment]
I just reviewed the starter code for Lab 7.  This method does exist in the MainResponses.cs class already.

![image](https://user-images.githubusercontent.com/9438237/83275719-64f8bf80-a184-11ea-9884-249f01810c57.png)

**Comment by iamalexmang** [comment]
Gerry, though it exists, all 30 students follow the existing labs as I’ve mentioned in the issue. Neither of the other labs have the method, as specified.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
