### ISSUE TITLE
Update Lab 7 finished sample code to understand the 'search' intent

### ISSUE THREAD

**Issue by iamalexmang** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#36]
The 'Search' intent is commented out and the bot thus doesn't understand the 'Search' intent in the starter code of the 7th lab. Superficially, this is in the Startup.cs file, in the Startup class, in the ConfigureServices method, on line 106.

``` c#
middleware.Add(new RegExpRecognizerMiddleware()
// search pics is not currently implemented and intended for future testing               
//.AddIntent("search", new Regex("search picture(?:s)*(.*)|search pic(?:s)*(.*)", RegexOptions.IgnoreCase))            
```

Since the instructions in these labs are building on each other and in Lab 4 students are expected to have used the search intent in the bot, it would only make sense for the code **NOT** to be commented. Otherwise, students who followed the labs entirely get a different experience than students who have started the lab using the starter sample.

**Comment by gerryaobrien** [comment]
Removed comment from line 106 so students can implement this without friction.
