### ISSUE TITLE
Lab 4- github code errors on running with LUIS

### ISSUE THREAD

**Issue by ac2707** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#4]
the code for lab 4 is not in continuation as left on lab 3.
LUIS code is present in the github code but no mention in lab 3 or 4 on the steps and it errors out on running

**Comment by leventorer** [comment]
Comment out line 51 in Startup.cs: middleware.Add(*LUIS*)
Then it does compile, and a web page opens, saying "PictureBot Describe your bot here and your terms of use etc.", but cannot connect to it with the Bot Framework Emulator

**Comment by givenscj** [comment]
The latest labs and updates have been posted, please let us know how you like them.
