### ISSUE TITLE
File too big in Lab05

### ISSUE THREAD

**Issue by tibor19** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#40]
Latest changes in QnA Marker free tier do not allow files bigger than 1 MB to be uploaded. Because of that code/surface-pro-4-user-guide-EN.pdf will not be accepted.

**Comment by gerryaobrien** [comment]
Stop breaking stuff Tibi.   :-)

Let me look into this.

**Comment by gerryaobrien** [comment]
I downloaded the Surface-pro-4-user-guide.pdf that is included in the lab materials and was able to create a QnA Maker service and upload the file into the knowledge base that was created.  I check the file size and it is 1,183 KB in size.

I am not able to repro your issue.

**Comment by tibor19** [comment]
Are you doing that on the Free tier?

**Comment by gerryaobrien** [comment]
You're right, I was using the next tier up for testing this.  Went to a personal account and ran into the issue.  Reduced the file size and uploaded the new version, tested and it works on the free tier.

**Comment by tibor19** [comment]
Sorry for breaking your stuff! :)

**Comment by gerryaobrien** [comment]
Somebody has to.   :-)
