### ISSUE TITLE
Lab 2.2 wrong link

### ISSUE THREAD

**Issue by jzagalmstecs** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#41]
# Lab 2.2: Resources
In this step ``"There are some directories in the main github repo folder:"`` the link **main** is wrong, this link redirect us to 

https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/blob/master/Lab2-Implement_Computer_Vision/Lab2-Implement_Computer_Vision

and the correct one should be:

https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/blob/master/Lab2-Implement_Computer_Vision/

**Comment by gerryaobrien** [comment]
Interesting, this is the second time I have fixed this link.
