### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#44]
In https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/blob/master/Lab3-Basic_Filter_Bot/02-Basic_Filter_Bot.md, following link is broken: {GitHubPath}/code/Finished/PictureBot-Part0.

**Comment by gerryaobrien** [comment]
This link is intended to point to the cloned version you have locally.   It is not intended to be an active link to the github.com repo.
