### ISSUE TITLE
Lab3, Invalid Operation Exception

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#45]
After finishing the steps in **Lab3** and double checking, I still get following error on the level of the line "app.UseMvc" when I run (build is fine):
`System.InvalidOperationException: 'Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).'`

Any update/fix?

**Comment by gerryaobrien** [comment]
Unable to repro this issue.

**Comment by houbena** [comment]
The misbehavior occurs when I start from scratch and follow the instructions, the project is generated using the lastest version of **VS EchoBot v4.9.2**.

Did you follow the same path @gerryaobrien ?

**Comment by gerryaobrien** [comment]
Which portion of Lab 3?  There are different sections.

**Comment by houbena** [comment]
This is when I run the bot, so at the end of this part "Lab 3.5: Running the bot"

**Comment by naghazal** [comment]
There a pull request about it: This workaround solved my issue

// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddNewtonsoftJson();

            services.AddMvc(option => option.EnableEndpointRouting = false);

**Comment by gerryaobrien** [comment]
There are no pull requests for this repo Nader.

**Comment by gerryaobrien** [comment]
Code was updated to address the PR.
