### ISSUE TITLE
Labs

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#47]
Hello 

I have been asked to teach this course. How solid are the labs? ie: do they actually work? 

Are there any errata documents for the course that show bugs in the notes or labs? 

Thanks

**Comment by gerryaobrien** [comment]
This is not an issue.  Please do not use this as a discussion forum.  The labs are intended to be taught by Microsoft Certified Trainers as part of the official curriculum.  If you an MCT, use the discussion groups available to you for this purpose.

**Comment by arnoldvilleneuve** [comment]
I am an MCT and asked a fair question. The same question was posted in the MCT forum. 




Get Outlook for Android







On Wed, Aug 26, 2020 at 1:22 PM -0400, "gerryaobrien" <notifications@github.com> wrote:















This is not an issue.  Please do not use this as a discussion forum.  The labs are intended to be taught by Microsoft Certified Trainers as part of the official curriculum.  If you an MCT, use the discussion groups available to you for this purpose.
