### ISSUE TITLE
Issue in Lab 2.6

### ISSUE THREAD

**Issue by Katelynnn-ai** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#51]
I encountered the error "C:\Program Files\dotnet\sdk\3.1.402\Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. 
I've installed 'dotnet-sdk-3.1.402-win-x64', but wasn't able to find the folder 'Portable\~'. 
Please anyone let me know how to get a 'Microsoft.Portable.CSharp.targets' file.

**Comment by gerryaobrien** [comment]
Please ensure that you follow the notes about installing .NET Core 2.2.

**Comment by Katelynnn-ai** [comment]
Hi gerryaobrien,
Thank you for your comment.
I've installed .NET Core 2.2 downloaded from https://dotnet.microsoft.com/download/dotnet-core/2.2 (both ASP.NET Core Runtime 2.2.8 / Build apps - SDK)
