### ISSUE TITLE
Issue in Lab3.5

### ISSUE THREAD

**Issue by Katelynnn-ai** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#52]
It seems like intent doesn't work.
![image](https://user-images.githubusercontent.com/71359536/93605400-a813c280-fa01-11ea-8a81-4a10bd2ab6e7.png)
I opened the solution from '../Lab4-Log_Chat/code/Finished/PictureBot/PictureBot.sln' which means I didn't change any code, I only updated 'appsetting.json' in order to update url/myappid/password and storage.

I expected the bot answers like below.
![image](https://user-images.githubusercontent.com/71359536/93605994-70f1e100-fa02-11ea-9a74-55b3505297ae.png)

What should I check?
Thank you in advance.

**Comment by true-while** [comment]
Yes, On the LAB 3.5 we do not have LUIS integration to provided you intent analyzing. It will be set up later in the labs 6 & 7.  The Photos will never comes from current implementation.

**Comment by Katelynnn-ai** [comment]
@true-while Thank you for your comments. Does searching for photos is implemented throughout this whole labs? If yes, please point me to the exact lab no. I finished the entire labs, but I wasn't able to implement it.
