### ISSUE TITLE
Running first time

### ISSUE THREAD

**Issue by joshuablanco** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#55]
Hi. I'm a newbie at this.
I noticed that the code is made in netcore2.2, I´d like to try to make a basic upgrade or running an easy version with 3.1 or something like that, it doesn't work with the 2.2 version in my visual, any suggestion? 
Thanks
Josh

**Comment by gerryaobrien** [comment]
I just merged a PR from one of our trainers to upgrade to .NET Core 3.1.  Take a look at the changes that were made today.

**Comment by joshuablanco** [comment]
Got it, thank you very much!

**Comment by gerryaobrien** [comment]
Good timing actually.  :-)
