### ISSUE TITLE
PictureBot rename

### ISSUE THREAD

**Issue by rvvincelli** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#58]
[Here](https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/blob/master/Lab3-Basic_Filter_Bot/02-Basic_Filter_Bot.md#lab-31-creating-a-simple-bot-and-running-it) we are invited to rename the project from `EchoBot` to `PictureBot`, warning that _renaming a Visual Studio Solution/Project is a very sensitive task_.

And indeed refactoring through the wizard gives me an error (Microsoft Visual Studio Community 2019 Version 16.6.2) because you get a clash at line 34 of `Startup.cs`:
`services.AddTransient<IBot, Bots.PictureBot>();`
as `PictureBot` is both the name of the main class and the namespace.

Renaming the main class to something else solves the issue.

Thanks,

**Comment by gerryaobrien** [comment]
Yes, changed the instructions to create the project as PictureBotProj to avoid the name conflict.
