### ISSUE TITLE
Direct Line configuration

### ISSUE THREAD

**Issue by rvvincelli** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#59]
No matter if I try to connect to the remote or local bot I get a 404 or 500 from the Direct Line component, and I cannot find the ID or key either.
![Capture](https://user-images.githubusercontent.com/3406087/96478440-f8b45080-1237-11eb-9da5-f91286fb44cf.PNG)

**Comment by gerryaobrien** [comment]
It's not possible to troubleshoot this issue because there isn't enough information to help you.

**Comment by rvvincelli** [comment]
This happens when I try to instrument the bot, following the guide exactly step by step. Thanks,

**Comment by rvvincelli** [comment]
Very classic, my app creds were wrong. Tx,
