### ISSUE TITLE
Timeline for re-work AI-100 Labs?

### ISSUE THREAD

**Issue by zfklnmgg** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#6]
Dear @gerryaobrien , dear MicrosoftLearning-Team, 

I am highly interested in fully functioning, up-to-date labs and descriptions for the AI-100 course. 

Unfortunately, this is currently not the case. The Azure environment and the code it outputs changed significantly since creation of this lab in April and differ significantly from the code samples shown here. This renders many labs outdated up to non-functioning and highly impedes the learning experience. Furthermore, several labs are non-existent. 

I am happy to see new activity going on in this respository. Kindly I would like to know, what your timeline for re-working the AI-100 labs is. 

Thank you very much for your work.

**Comment by gerryaobrien** [comment]
The lab content is being reviewed and refreshed to reflect changes in the services used.  Labs that are indicated as under construction will also be completed.

Current expected time frame puts us around and August or September time frame by the time content is created, refreshed, and tested.

**Comment by givenscj** [comment]
The latest labs and updates have been posted, please let us know how you like them.
