### ISSUE TITLE
'The version of the selected solution is higher then the solution version supported by the Visual Studio release' in some .slns

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#66]
After the recent code update, it appears that a small subset of the .sln files have an odd 'MinimumVisualStudioVersion = **16.0.30503.244**' that appears to conflict with at least some versions of Visual Studio 2019, preventing their successful opening of the solutions and leading to the '_The version of the selected solution is higher then the solution version supported by the Visual Studio release_' error message.

While a VS2019 upgrade may also resolve for this issue - a suggested interim fix of modifying that value to 'MinimumVisualStudioVersion = **10.0.40219.1**' - in cases where upgrades are not initially feasible - also appears to work to allow the solutions to be opened without error.

Is this something that can/should be corrected within the GH versions of those .slns in order to avoid the problem altogether?

This is a list of the subset of .slns that seem to have the 'issue':

Lab9-Test_Bots_DirectLine\code\Starter\PictureBot\PictureBot.sln
Lab8-Detect_Language\code\Starter\PictureBot\PictureBot.sln
Lab8-Detect_Language\code\Finished\PictureBot\PictureBot.sln
Lab7-Integrate_LUIS\code\Starter\PictureBot\PictureBot.sln
Lab7-Integrate_LUIS\code\Finished\PictureBot\PictureBot.sln
Lab4-Log_Chat\code\Starter\PictureBot\PictureBot.sln
Lab4-Log_Chat\code\Finished\PictureBot\PictureBot.sln
Lab3-Basic_Filter_Bot\code\Finished\PictureBot\PictureBot.sln

**Comment by gerryaobrien** [comment]
This should be fixed now with the latest solution files.
